### PR TITLE
update build script

### PR DESCRIPTION
**Pull request by edge**

### CODE REVIEW

**Comment by Marionumber1** [comment]
1. I don't think Java is a language we need to build support for.
2. Can you make it re-run the script after downloading Binutils and GCC?

**Comment by edge** [comment]
I did this right afterwards, anyways. It looks much nicer, and it's easy to just add a line to make it rerun.

```sh
./$0
```

https://github.com/edge/cross

**Comment by theoduino** [comment]
Or, you could just use Arch Linux and the AUR
https://aur.archlinux.org/packages/i686-elf-gcc

**Comment by Marionumber1** [comment]
*looks at issue comment*
*sees Theo suggest I use Linux*
*bursts out laughing*

**Pull request closed without merging**
